# Generated by Django 5.1.6 on 2025-03-15 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estanque', models.CharField(max_length=100)),
                ('profundidad_agua', models.FloatField()),
                ('largo', models.FloatField()),
                ('ancho', models.FloatField()),
                ('species', models.CharField(max_length=100)),
                ('cantidad_peces', models.IntegerField()),
                ('etapa', models.CharField(max_length=100)),
                ('tipo_concentrado', models.CharField(max_length=100)),
                ('temperatura_estanque', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=100)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
