# Generated by Django 5.1.6 on 2025-03-15 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_concentrado_actual', models.CharField(max_length=100)),
                ('nombre_procedimiento', models.CharField(max_length=100)),
                ('descripcion_procedimiento', models.TimeField()),
                ('observaciones', models.TimeField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_management.fish')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
